<h1 class="font-heading text-3xl md:text-5xl text-center font-black">Hi! I'm Pranav!</h1>

	<p> 
	Welcome to my site. My research papers and current work are collected on the
	<a href="/projects" class="text-primary-400 hover:text-primary-300 underline">Projects page</a>.
	To return to this page, click my name at the top on any page. 
	If you'd like to contact me, you can use the link in the footer. 
	</p>

	<p>
	The website icon I'm using was generated by DALL-E 3, 
	with the prompt being something along the lines 
	"fire and the stars in a neoclassical art style."
	</p>
