<h1 class="font-heading text-5xl text-center font-black">Hi! I'm Pranav!</h1>

	<p> 
	Welcome to my site. You can find out about myself, 
	my writing, and my projects by using the links above.
	The blog page links to my Substack, which you can 
	subscribe to for updates whenever I post. 
	To return to this page, click my name at the top on any page. 
	If you'd like to contact me, you can use the link in the footer. 
	</p>

	<p>
	The website icon I'm using was generated by DALL-E 3, 
	with the prompt being something along the lines 
	"fire and the stars in a neoclassical art style."
	</p>
